In [1]:
import numpy as np

In [2]:
first = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
print(f"One dimensional array: {first}")

One dimensional array: [1 2 3 4 5 6 7 8 9]


In [4]:
second = np.array([[1,2,3], [4,5,6]])

print(f"Multi dimensional array: {second}")

Multi dimensional array: [[1 2 3]
 [4 5 6]]


In [5]:
# Creating arrays full of zeros

zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Creating arrays full of ones

ones = np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# Creating array of empty spaces

null = np.empty([3,4])
null

array([[2.21230501e-316, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.06099790e-312, 1.03977794e-312, 1.23075756e-312,
        1.14587773e-312],
       [1.08221785e-312, 9.76118064e-313, 1.08221785e-312,
        1.90979621e-312]])